/** @type {import('tailwindcss').Config} */
export default {
  content: ["./*.html", "./src/**/*.{js,ts}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#a1d1fe",
        "on-primary-fixed": "#003351",
        "secondary-fixed-dim": "#c6d6e8",
        "surface-dim": "#d5dae3",
        outline: "#757b83",
        surface: "#f8f9fe",
        "on-background": "#2d3339",
        error: "#a83836",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f8f9fe",
        "primary-container": "#a1d1fe",
        "on-secondary-fixed": "#32414f",
        "primary-fixed-dim": "#93c3ef",
        "on-tertiary": "#fbf7ff",
        "error-container": "#fa746f",
        "tertiary-dim": "#504f78",
        "on-tertiary-fixed": "#2d2c53",
        "secondary-fixed": "#d4e4f6",
        "on-secondary": "#f6f9ff",
        "on-tertiary-fixed-variant": "#494971",
        "inverse-primary": "#a1d1fe",
        "on-primary": "#f6f9ff",
        "tertiary-container": "#cac7f8",
        "surface-variant": "#dde3eb",
        background: "#f8f9fe",
        "primary-dim": "#22577e",
        "on-error-container": "#6e0a12",
        "tertiary-fixed-dim": "#bcbae9",
        "on-tertiary-container": "#404068",
        "on-primary-fixed-variant": "#1a5177",
        "inverse-on-surface": "#9b9da1",
        "surface-container-high": "#e4e8f0",
        "on-secondary-container": "#445362",
        "surface-container-low": "#f1f4f9",
        secondary: "#526170",
        "surface-tint": "#31638a",
        primary: "#31638a",
        "secondary-dim": "#465563",
        "outline-variant": "#adb2ba",
        "surface-container": "#eaeef5",
        tertiary: "#5c5b85",
        "tertiary-fixed": "#cac7f8",
        "on-error": "#fff7f6",
        "on-surface": "#2d3339",
        "inverse-surface": "#0c0e11",
        "error-dim": "#67040d",
        "on-secondary-fixed-variant": "#4e5d6c",
        "surface-container-highest": "#dde3eb",
        "on-surface-variant": "#5a6067",
        "secondary-container": "#d4e4f6",
        "on-primary-container": "#0a476d",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "Cairo", "sans-serif"],
        body: ["Plus Jakarta Sans", "Cairo", "sans-serif"],
        label: ["Plus Jakarta Sans", "Cairo", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
